name = "prometheus"

[[services]]
  name = "server"
  image = "docker.io/prom/prometheus:latest"
  replicas = 1
  [services.process]
    args = [
      "/bin/prometheus",
      "--config.file=/etc/prometheus/prometheus.yml",
      "--web.enable-remote-write-receiver",
    ]
  [services.network]
    type = "stellar"
  [[services.configs]]
    name = "prometheus"
    path = "/etc/prometheus/prometheus.yml"
    content = '''# managed by stellar
global:
  scrape_interval:     15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
'''
