name = "hello"

[[services]]
  name = "nginx"
  image = "docker.io/nginxdemos/hello:plain-text"
  replicas = 2
  [services.network]
    type = "stellar"
  [services.placementPreference]
    strategy = "spread"
  [[services.endpoints]]
    [services.endpoints.config]
      [services.endpoints.config.http]
        host = "{{ if ne (index .Params \"domain\") \"\" }}{{ index .Params \"domain\" }}{{ else }}hello.stellar.local{{ end }}"
        port = 80
