name = "fusion"
[labels]
  "stellar.application" = "fusion"

[[services]]
  name = "lb"
  image = "docker.io/axyon/fusion:latest"
  pull = true
  replicas = 2
  [services.process]
    args = [
      "fusion",
      "server",
      "-c",
      "/etc/fusion.toml",
    ]
  [services.network]
    type = "stellar"
  [services.placementPreference]
    strategy = "spread"
  [[services.configs]]
    name = "fusion-config"
    path = "/etc/fusion.toml"
    content = '''# stellar fusion
StellarAddress = {{ if ne (index .Params "api-endpoint") "" }}"{{ index .Params "api-endpint" }}"{{ else }}"10.50.255.1:8080"{{ end }}
HTTPAddress = ":80"
EnableProxyHeaders = true
'''
