name = "buildkit"
[labels]
  "stellar.application" = "buildkit"

[[services]]
  name = "app"
  image = "docker.io/moby/buildkit:buildx-stable-1"
  replicas = 1
  privileged = true
  [services.process]
    args = ["/usr/local/bin/run.sh"]
  [services.network]
    type = "stellar"
  [[services.mounts]]
    type = "bind"
    source = "/sys"
    destination = "/sys"
    options = ["rbind", "rw"]
  [[services.endpoints]]
    [services.endpoints.config]
      [services.endpoints.config.tcp]
        port = 9000
  [[services.configs]]
    name = "buildkit-run"
    path = "/usr/local/bin/run.sh"
    mode = "0755"
    content = '''# stellar buildkit
exec buildkitd --addr tcp://0.0.0.0:9000 {{ if ne (index .Params "args") "" }}{{ index .Params "args" }} {{ end }}
'''
